services:
  db:
    image: emmanueljprime/gestion-produits-db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    image: emmanueljprime/gestion-produits-php
    restart: always
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - uploads_data:/var/www/html/uploads

volumes:
  mysql_data:
  uploads_data:
